// <auto-generated />
namespace Team7_LonghornMusic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ShoppingCartStuff : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ShoppingCartStuff));
        
        string IMigrationMetadata.Id
        {
            get { return "201611220040581_ShoppingCartStuff"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
